"""Supabase trade/event logging via the PostgREST API.

Schema is created once via the Supabase Management API (uses the personal access
token). Row inserts use the project's service key against /rest/v1.
"""
from __future__ import annotations

import json
from typing import Any, Optional

import requests

from recycler.config import Settings, load_settings

SCHEMA_SQL = """
create table if not exists public.trades (
  id           bigint generated by default as identity primary key,
  ts           timestamptz default now(),
  mode         text,
  symbol       text,
  direction    int,
  entry_time   timestamptz,
  exit_time    timestamptz,
  entry        double precision,
  exit_price   double precision,
  stop         double precision,
  size_lots    double precision,
  pnl          double precision,
  r_multiple   double precision,
  reason       text,
  risk_pct     double precision,
  equity_after double precision,
  tag          text,
  meta         jsonb
);
create table if not exists public.bot_events (
  id      bigint generated by default as identity primary key,
  ts      timestamptz default now(),
  level   text,
  kind    text,
  message text,
  meta    jsonb
);
"""


def _project_ref(url: str) -> str:
    # https://<ref>.supabase.co
    return url.split("//", 1)[-1].split(".", 1)[0]


class Supabase:
    def __init__(self, settings: Settings | None = None):
        self.s = settings or load_settings()
        self.rest = f"{self.s.supabase_url}/rest/v1"
        self.key = self.s.supabase_service_key
        self.enabled = bool(self.s.supabase_url and self.key)

    # ---- one-time schema via Management API (needs SUPABASE_ACCESS_TOKEN) ----
    def ensure_schema(self) -> bool:
        import os
        token = os.environ.get("SUPABASE_ACCESS_TOKEN", "")
        if not token:
            print("[supabase] SUPABASE_ACCESS_TOKEN not set; create tables manually.")
            return False
        ref = _project_ref(self.s.supabase_url)
        try:
            r = requests.post(
                f"https://api.supabase.com/v1/projects/{ref}/database/query",
                headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                data=json.dumps({"query": SCHEMA_SQL}), timeout=30)
            ok = r.status_code in (200, 201)
            print(f"[supabase] ensure_schema status={r.status_code} {('OK' if ok else r.text[:200])}")
            return ok
        except Exception as e:
            print("[supabase] ensure_schema error:", e)
            return False

    def _headers(self) -> dict:
        return {"apikey": self.key, "Authorization": f"Bearer {self.key}",
                "Content-Type": "application/json", "Prefer": "return=minimal"}

    def insert(self, table: str, row: dict[str, Any]) -> bool:
        if not self.enabled:
            return False
        try:
            r = requests.post(f"{self.rest}/{table}", headers=self._headers(),
                              data=json.dumps([row], default=str), timeout=20)
            ok = r.status_code in (200, 201, 204)
            if not ok:
                print(f"[supabase] insert {table} failed {r.status_code}: {r.text[:200]}")
            return ok
        except Exception as e:
            print("[supabase] insert error:", e)
            return False

    def log_trade(self, **kw) -> bool:
        return self.insert("trades", kw)

    def log_event(self, level: str, kind: str, message: str,
                  meta: Optional[dict] = None) -> bool:
        return self.insert("bot_events", {"level": level, "kind": kind,
                                          "message": message, "meta": meta})
